info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/getUserList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - userservice
swagger: "2.0"
